### ISSUE TITLE
No plugin was found for the accessory "LinkyMeter" in your config.json. Please make sure the corresponding plugin is installed correctly.

### ISSUE THREAD

**Issue by GDeb59** [tthma/homebridge-linky-enedis-meter#1]
Hello, 

Tout d'abord un grand merci à toi pour ce plugin.

J'ai ce message dans les logs :
[10/5/2022, 7:13:09 PM] No plugin was found for the accessory "LinkyMeter" in your config.json. Please make sure the corresponding plugin is installed correctly.

Via Homebridge / Terminal je récupère bien l'info conso :

root@Docker:/var/lib/homebridge $ linky daily
✔ Récupération de la consommation quotidienne

Date        Valeur (Wh) Graphique                     
2022-10-04  7008        ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
root@Docker:/var/lib/homebridge $ 

Infos : 
Homebridge 1.5.0
NodeJS : 16.16.0
Sous Docker

**Comment by tthma** [comment]
En gros ça veux dire qu'il cherche un appareil qui s'appelle "linkymeter" mais qui ne le trouve pas il faut que accesory:"linkymeter".
J'ai eu ce soucis aussi mais ça l'empêchait pas de fonctionner 

Y a quoi qui apparaît dans accessory ?
Dans la config home bridge ?

**Comment by GDeb59** [comment]
Dans mon config.json j'ai bien : 

{
            "name": "Linky Meter",
            "usagePointId": "myusagePointId",
            "accessToken": "myaccessToken",
            "refreshToken": "myrefreshToken",
            "update_interval": 10000,
            "accessory": "LinkyMeter"
        }

Y'a rien dans l'onglet Accessoires correspondant à Linky Meter.

**Comment by tthma** [comment]
Changer linkymeter par energymeter comme indiqué dans le readme
Ça devrait fonctionner 
Tenez moi au courant

**Comment by GDeb59** [comment]
C'est mieux 👍 

Par contre ça tourne en boucle maintenant.

[10/5/2022, 8:34:04 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:04 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:04 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:34:04 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:04 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:09 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:09 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:09 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:34:14 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:34:14 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:14 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:19 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:19 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:19 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:34:24 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:34:24 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:24 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:29 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:29 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:29 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:34:34 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:34:39 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:34:39 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:39 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:44 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:44 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:44 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:34:44 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:44 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:49 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:49 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:49 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:34:54 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:34:54 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:54 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:34:59 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:34:59 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:34:59 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:35:04 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:35:07 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:07 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:09 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:35:09 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:35:09 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:35:14 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!
[10/5/2022, 8:35:14 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:14 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:19 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:35:19 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:35:19 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:35:19 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:19 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:24 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:35:24 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:35:24 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:35:24 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:24 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:29 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:35:29 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:35:29 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:35:31 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:31 PM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/5/2022, 8:35:34 PM] [Linky Meter] 1664928000000
[10/5/2022, 8:35:34 PM] [Linky Meter] 2022-10-12T00:00:00.000Z
[10/5/2022, 8:35:34 PM] [Linky Meter] Query start = 2022-10-05 End = 2022-10-06
[10/5/2022, 8:35:39 PM] [Linky Meter] Please select a higher update_interval value. Http command may not finish!

**Comment by tthma** [comment]
Arf! 
Là il essaye de savoir la consommation de demain donc il est pas content !

Restart homebrige et/ou reset dans Ève app "mesure" (le petit i bleu) je regarderai demain là le pc est éteint 

Faut que je rajoute une sécu pour pas que la date sois supérieur au jours d'après en gros

Je fais une maj demain dans la journée

**Comment by tthma** [comment]
Mise a jour ok.

j'ai refait l'interface de configuration pour plus de facilité a paramétré le plugin

**Comment by GDeb59** [comment]
[homebridge.log.txt](https://github.com/tthma/homebridge-linky-enedis-meter/files/9726304/homebridge.log.txt)

J'ai mis à jour. Malgré les quelques warnings au début, ça s'était pas trop mal passé puis ça a fait crashé Homebridge.
Et quand ça a redémarré, ça a bouclé tout le temps sur la même période.

**Comment by tthma** [comment]
😑 on va pas s'en sortir !

Bizarre il tourne en boucle sur la première date de réception.
L'erreur 500 ça viens du serveur Enedis sont pas tjr eau top.

Le httprequest Timeout ça veux dire qu'il a bouclé sans avoir de retour peut être voir à augmenter dans le config.json le temps de bouclage.

Question est-ce que dans le config.json vous avez mis la première date ou enedis a commencer à récolter les données ? (Cf config dans le readme) champ firstdatevalue ou un truc dans le genre j'ai pas le champ en tête là

**Comment by GDeb59** [comment]
![Capture d’écran 2022-10-06 à 18 14 46](https://user-images.githubusercontent.com/59055140/194365229-cf79018f-e30b-4043-8351-dc8ab4da9efb.png)

Finalement, j'ai restauré Homebridge à avant hier et réinstallé le plugin.
J'ai des données dans l'app Eve.

Sur la journée du 14/09 je suis censé avoir 10,4kWh en conso journalière.
Sur Eve app j'ai 3,45kwh

![IMG_0151](https://user-images.githubusercontent.com/59055140/194365918-983a263c-6733-4f20-bdb3-107483a02fa2.PNG)

**Comment by GDeb59** [comment]
> 😑 on va pas s'en sortir !
> 
> Bizarre il tourne en boucle sur la première date de réception. L'erreur 500 ça viens du serveur Enedis sont pas tjr eau top.
> 
> Le httprequest Timeout ça veux dire qu'il a bouclé sans avoir de retour peut être voir à augmenter dans le config.json le temps de bouclage.
> 
> Question est-ce que dans le config.json vous avez mis la première date ou enedis a commencer à récolter les données ? (Cf config dans le readme) champ firstdatevalue ou un truc dans le genre j'ai pas le champ en tête là

J'ai mis 2022-01-01 pour le firstDateRecord à : "firstDateRecord": "2022-01-01T00:00:00Z"
mais dans les logs Homebridge, je voyais que ça récupérait les datas semaine par semaine et ça a pris les données d'une année (from 2021-10-05).

**Comment by tthma** [comment]
Faut regarder dans le champ mesure si tout est là sinon pendant que homebridge tourne encore faut supprimer les mesures dans Ève app et appuyer sur le bouton reset de Ève après 

Il récupère toute les demi heure ou heure en fonction depuis la date firstdate record

Je fait tourner sur un pi j'ai pas de problème mise à part qu'au premier lancement ça met 20ans à tout récupérer.

De plus la synchronisation entre Ève et homebridge est archi long.
Mais normalement il oublie pas des valeurs

**Comment by tthma** [comment]
Quand on appuie sur le bouton reset ça efface l'historique persistant et ça repars de Firsdatevalue et ça re boucle jusqu'à aujourd'hui

**Comment by tthma** [comment]
je me répond à moi même ça me travail cette histoire...

J'ai cerné le problème de date qui tourne en boucle je corrige ça demain et je refait une mise à jour 

Merci à toi de m'aider à faire un truc qui plante pas !
Par contre le oof je sais pas là encore le pourquoi du comment.

Je test sur mon pc et j'ai 15go de ram donc pas de oof et mon rasbery 3,75go j'ai pas de soucis la dessus non plus

**Comment by tthma** [comment]
Normalement l'ensemble des problèmes on été corrigé avec la dernière version
