### ISSUE TITLE
Probleme

### ISSUE THREAD

**Issue by Gabin85** [tthma/homebridge-linky-enedis-meter#16]
En allant sur homebridge pour mettre à jour mes plugins j'ai remarqué de gros message rouge d'erreur...

` APIError: Conso API a répondu avec une erreur
    at file:///homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/lib/index.js:76:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  err: AxiosError: Request failed with status code 403
      at settle (file:///homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/axios/lib/core/settle.js:19:12)
      at BrotliDecompress.handleStreamEnd (file:///homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/axios/lib/adapters/http.js:572:11)
      at BrotliDecompress.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: 'http',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'get',
      url: 'https://conso.boris.sh/api/consumption_load_curve?start=2023-09-20&end=2023-09-21&prm=',
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET /api/consumption_load_curve?start=2023-09-20&end=2023-09-21&prm= HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Authorization: Bearer  +
        'User-Agent: @bokub/linky\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: conso.boris.sh\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/consumption_load_curve?start=2023-09-20&end=2023-09-21&prm=',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'conso.boris.sh',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 403,
      statusText: 'Forbidden',
      headers: [Object [AxiosHeaders]],
      config: [Object],
      request: [ClientRequest],
      data: '<!DOCTYPE html>\n' +
        '\n' +
        '\n' +
        '\n' +
        ' <html class="no-js" lang="en-US"> \n' +
        '<head>\n' +
        '<title>Attention Required! | Cloudflare</title>\n' +
        '<meta charset="UTF-8" />\n' +
        '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n' +
        '<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n' +
        '<meta name="robots" content="noindex, nofollow" />\n' +
        '<meta name="viewport" content="width=device-width,initial-scale=1" />\n' +
        '<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />\n' +
        `<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->\n` +
        '<style>body{margin:0;padding:0}</style>\n' +
        '\n' +
        '\n' +
        '\n' +
        '<script>\n' +
        '  if (!navigator.cookieEnabled) {\n' +
        "    window.addEventListener('DOMContentLoaded', function () {\n" +
        "      var cookieEl = document.getElementById('cookie-alert');\n" +
        "      cookieEl.style.display = 'block';\n" +
        '    })\n' +
        '  }\n' +
        '</script>\n' +
        '\n' +
        '\n' +
        '\n' +
        '</head>\n' +
        '<body>\n' +
        '  <div id="cf-wrapper">\n' +
        '    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n' +
        '    <div id="cf-error-details" class="cf-error-details-wrapper">\n' +
        '      <div class="cf-wrapper cf-header cf-error-overview">\n' +
        '        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>\n' +
        '        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> boris.sh</h2>\n' +
        '      </div>\n' +
        '\n' +
        '      <div class="cf-section cf-highlight">\n' +
        '        <div class="cf-wrapper">\n' +
        '          <div class="cf-screenshot-container cf-screenshot-full">\n' +
        '            \n' +
        '              <span class="cf-no-screenshot error"></span>\n' +
        '            \n' +
        '          </div>\n' +
        '        </div>\n' +
        '      </div>\n' +
        '\n' +
        '      <div class="cf-section cf-wrapper">\n' +
        '        <div class="cf-columns two">\n' +
        '          <div class="cf-column">\n' +
        '            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>\n' +
        '\n' +
        '            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n' +
        '          </div>\n' +
        '\n' +
        '          <div class="cf-column">\n' +
        '            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>\n' +
        '\n' +
        '            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n' +
        '          </div>\n' +
        '        </div>\n' +
        '      </div>\n' +
        '\n' +
        '      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n' +
        '  <p class="text-13">\n' +
        '    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">80a58777fac502b1</strong></span>\n' +
        '    <span class="cf-footer-separator sm:hidden">&bull;</span>\n' +
        '    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">\n' +
        '      Your IP:\n' +
        '      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>\n' +
        '      <span class="hidden" id="cf-footer-ip">2a01:cb05:8820:c100:dea6:32ff:fe91:ecb5</span>\n' +
        '      <span class="cf-footer-separator sm:hidden">&bull;</span>\n' +
        '    </span>\n' +
        '    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>\n' +
        '    \n' +
        '  </p>\n' +
        '  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>\n' +
        '</div>\n' +
        '\n' +
        '\n' +
        '    </div>\n' +
        '  </div>\n' +
        '\n' +
        '  <script>\n' +
        '  window._cf_translation = {};\n' +
        '  \n' +
        '  \n' +
        '</script>\n' +
        '\n' +
        '</body>\n' +
        '</html>\n'
    }
  },
  code: 403,
  response: '<!DOCTYPE html>\n' +
    '\n' +
    '\n' +
    '\n' +
    ' <html class="no-js" lang="en-US"> \n' +
    '<head>\n' +
    '<title>Attention Required! | Cloudflare</title>\n' +
    '<meta charset="UTF-8" />\n' +
    '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n' +
    '<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n' +
    '<meta name="robots" content="noindex, nofollow" />\n' +
    '<meta name="viewport" content="width=device-width,initial-scale=1" />\n' +
    '<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />\n' +
    `<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->\n` +
    '<style>body{margin:0;padding:0}</style>\n' +
    '\n' +
    '\n' +
    '\n' +
    '<script>\n' +
    '  if (!navigator.cookieEnabled) {\n' +
    "    window.addEventListener('DOMContentLoaded', function () {\n" +
    "      var cookieEl = document.getElementById('cookie-alert');\n" +
    "      cookieEl.style.display = 'block';\n" +
    '    })\n' +
    '  }\n' +
    '</script>\n' +
    '\n' +
    '\n' +
    '\n' +
    '</head>\n' +
    '<body>\n' +
    '  <div id="cf-wrapper">\n' +
    '    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n' +
    '    <div id="cf-error-details" class="cf-error-details-wrapper">\n' +
    '      <div class="cf-wrapper cf-header cf-error-overview">\n' +
    '        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>\n' +
    '        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> boris.sh</h2>\n' +
    '      </div>\n' +
    '\n' +
    '      <div class="cf-section cf-highlight">\n' +
    '        <div class="cf-wrapper">\n' +
    '          <div class="cf-screenshot-container cf-screenshot-full">\n' +
    '            \n' +
    '              <span class="cf-no-screenshot error"></span>\n' +
    '            \n' +
    '          </div>\n' +
    '        </div>\n' +
    '      </div>\n' +
    '\n' +
    '      <div class="cf-section cf-wrapper">\n' +
    '        <div class="cf-columns two">\n' +
    '          <div class="cf-column">\n' +
    '            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>\n' +
    '\n' +
    '            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n' +
    '          </div>\n' +
    '\n' +
    '          <div class="cf-column">\n' +
    '            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>\n' +
    '\n' +
    '            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n' +
    '          </div>\n' +
    '        </div>\n' +
    '      </div>\n' +
    '\n' +
    '      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n' +
    '  <p class="text-13">\n' +
    '    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">80a58777fac502b1</strong></span>\n' +
    '    <span class="cf-footer-separator sm:hidden">&bull;</span>\n' +
    '    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">\n' +
    '      Your IP:\n' +
    '      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>\n' +
    '      <span class="hidden" id="cf-footer-ip">2a01:cb05:8820:c100:dea6:32ff:fe91:ecb5</span>\n' +
    '      <span class="cf-footer-separator sm:hidden">&bull;</span>\n' +
    '    </span>\n' +
    '    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>\n' +
    '    \n' +
    '  </p>\n' +
    '  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>\n' +
    '</div>\n' +
    '\n' +
    '\n' +
    '    </div>\n' +
    '  </div>\n' +
    '\n' +
    '  <script>\n' +
    '  window._cf_translation = {};\n' +
    '  \n' +
    '  \n' +
    '</script>\n' +
    '\n' +
    '</body>\n' +
    '</html>\n'`

**Comment by Gabin85** [comment]
Ah bah j'ai été banni par l'API -_-

**Comment by tthma** [comment]
Ça me faisait la même chose chez Bouygues.
Certains site ou j'étais bloqué je ne pouvais carrément pas y aller.
J'étais pas banni juste par la box ça marchait pas.
EDF impôt etc...
Des fois ça revenait et des fois non 😑

Vous êtes à quel version ?

**Comment by Gabin85** [comment]
Version de ? Tout est à jour de toute façon 

et je suis chez Orange

**Comment by phis5533** [comment]
Bonsoir, 
j'ai le même problème, même erreur alors que j'ai 2 compteurs pour un même compte Enedis et le deuxième fonctionne (sur une autre instance homebridge) et le premier a fonctionné, mais plus rien maintenant... 😬 
J'ai tout à jour aussi et suis chez Orange aussi.
Bizarre... 

PS : qu'est ce qui vous fait dire que vous êtes banni ? L'erreur 403 ?

**Comment by tthma** [comment]
Oula ! J'ai lâché l'affaire avec ce module depuis un moment !
J'avoue que j'avais plus le temps de me pencher dessus savoir si ça fonctionnait encore ou pas.
Je sais que ennedis on changé leur api et je me suis jamais re pencher sur la question.
Je suis même étonné de voir que pour certains il fonctionne encore 🤣

À l'occasion je regarderai si je peux pas le refaire marcher ce truc

**Comment by phis5533** [comment]
Je confirme le blacklist !
Si je change d’ip ca fonctionne parfaitement….
Merci ☺️

**Comment by tthma** [comment]
> Je confirme le blacklist !
> 
> Si je change d’ip ca fonctionne parfaitement….
> 
> Merci ☺️ 

En fait l'api d'enedis est très suceptible.
Faut y aller vraiment molo et pas faire des appels toute les 5min sinon il ban

**Comment by Gabin85** [comment]
J’ai aussi abandonné, le plugin est désactivé dans mon homebridge, j’ai beau changé d’IP, je me fais toujours ban par l’API même en augmentant les délais

**Comment by tthma** [comment]
De mon côté c'est même pas enedis qui me ban c'est Bouygues telecom 
En réseau chez moi je n'arrive pas à me co sur les sites gouvernementaux ameli EDF etc etc
